name: 'Publish'

on:
  push:
    branches: ['main']

jobs:
  lint:
    name: 'Run ESLint and Prettier'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the lint script'
        run: 'npm run lint'

  test:
    name: 'Run unit tests with Jest'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the test script'
        run: 'npm run test'

  generate_doc:
    name: 'Generate Api document with typedoc'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the doc script'
        run: 'npm run doc'

  bundle:
    name: 'Bundle package with Rollup.js'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the build script'
        run: 'npm run build'

  deploy:
    name: 'Deploy bundled package to npm'
    needs: [ 'lint', 'test', 'generate_doc', 'bundle' ]
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Setup Node.js and npm'
        uses: './.github/actions/setup'

      - name: 'Execute the publish script'
        run: 'npm publish'
        shell: 'bash'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
